"""Tests for recommendation writer — marker-based file updates."""

from pathlib import Path

from headroom.learn.models import ProjectInfo, Recommendation, RecommendationTarget
from headroom.learn.writer import (
    _MARKER_END,
    _MARKER_START,
    ClaudeCodeWriter,
    _parse_prior_recommendations,
    extract_marker_block,
)


def _project(tmp_path: Path) -> ProjectInfo:
    proj_dir = tmp_path / "myproject"
    proj_dir.mkdir()
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    memory_dir = data_dir / "memory"
    memory_dir.mkdir()
    return ProjectInfo(
        name="myproject",
        project_path=proj_dir,
        data_path=data_dir,
    )


def _rec(target: RecommendationTarget, section: str, content: str) -> Recommendation:
    return Recommendation(
        target=target, section=section, content=content, confidence=0.8, evidence_count=5
    )


class TestClaudeCodeWriter:
    def test_dry_run_does_not_write(self, tmp_path):
        proj = _project(tmp_path)
        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.CONTEXT_FILE, "Environment", "- Use uv")]

        result = writer.write(recs, proj, dry_run=True)

        assert result.dry_run is True
        assert len(result.files_written) == 1
        # File should NOT exist (dry run)
        claude_md = proj.project_path / "CLAUDE.md"
        assert not claude_md.exists()

    def test_apply_writes_claude_md(self, tmp_path):
        proj = _project(tmp_path)
        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.CONTEXT_FILE, "Environment", "- Use `uv run python`")]

        result = writer.write(recs, proj, dry_run=False)

        assert result.dry_run is False
        claude_md = proj.project_path / "CLAUDE.md"
        assert claude_md.exists()
        content = claude_md.read_text()
        assert "uv run python" in content
        assert _MARKER_START in content
        assert _MARKER_END in content

    def test_apply_writes_memory_md(self, tmp_path):
        proj = _project(tmp_path)
        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.MEMORY_FILE, "Retry Prevention", "- Don't retry globs")]

        writer.write(recs, proj, dry_run=False)

        memory_md = proj.data_path / "memory" / "MEMORY.md"
        assert memory_md.exists()
        assert "Don't retry globs" in memory_md.read_text()

    def test_preserves_existing_claude_md_content(self, tmp_path):
        proj = _project(tmp_path)
        claude_md = proj.project_path / "CLAUDE.md"
        claude_md.write_text("# My Project\n\nExisting instructions here.\n")

        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.CONTEXT_FILE, "Environment", "- Use uv")]
        writer.write(recs, proj, dry_run=False)

        content = claude_md.read_text()
        assert "My Project" in content
        assert "Existing instructions here" in content
        assert "Use uv" in content

    def test_carries_forward_prior_sections_not_resurfaced(self, tmp_path):
        """Re-running learn must not drop prior sections that the new run didn't re-surface."""
        proj = _project(tmp_path)
        claude_md = proj.project_path / "CLAUDE.md"
        prior_block = (
            f"# My Project\n\n{_MARKER_START}\n"
            "## Headroom Learned Patterns\n"
            "*Auto-generated by `headroom learn` on 2026-01-01 — do not edit manually*\n\n"
            "### Large Files\n"
            "*~15,000 tokens/session saved*\n"
            "- src/App.tsx is huge\n\n"
            "### Build Commands\n"
            "- cargo check from src-tauri/\n\n"
            f"{_MARKER_END}\n"
        )
        claude_md.write_text(prior_block)

        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.CONTEXT_FILE, "Environment", "- Use uv")]
        writer.write(recs, proj, dry_run=False)

        content = claude_md.read_text()
        assert "My Project" in content
        # New section present
        assert "Use uv" in content
        # Prior sections preserved (neither heading re-surfaced by the new run)
        assert "### Large Files" in content
        assert "src/App.tsx is huge" in content
        assert "### Build Commands" in content
        assert "cargo check from src-tauri/" in content
        # Tokens annotation round-tripped
        assert "*~15,000 tokens/session saved*" in content
        # Still exactly one marker pair
        assert content.count(_MARKER_START) == 1
        assert content.count(_MARKER_END) == 1

    def test_new_run_overrides_same_named_prior_section(self, tmp_path):
        """When a section appears in both prior and new, the new run wins."""
        proj = _project(tmp_path)
        claude_md = proj.project_path / "CLAUDE.md"
        prior_block = (
            f"{_MARKER_START}\n"
            "## Headroom Learned Patterns\n"
            "*Auto-generated by `headroom learn` on 2026-01-01 — do not edit manually*\n\n"
            "### Environment\n"
            "- old stale environment note\n\n"
            f"{_MARKER_END}\n"
        )
        claude_md.write_text(prior_block)

        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.CONTEXT_FILE, "Environment", "- fresh environment note")]
        writer.write(recs, proj, dry_run=False)

        content = claude_md.read_text()
        assert "fresh environment note" in content
        assert "old stale environment note" not in content
        # Only one Environment section in the final block
        assert content.count("### Environment") == 1

    def test_memory_md_carry_forward(self, tmp_path):
        """Carry-forward also works for MEMORY.md."""
        proj = _project(tmp_path)
        memory_md = proj.data_path / "memory" / "MEMORY.md"
        memory_md.write_text(
            f"{_MARKER_START}\n"
            "## Headroom Learned Patterns\n"
            "*Auto-generated by `headroom learn` on 2026-01-01 — do not edit manually*\n\n"
            "### User Workflow Preferences\n"
            "- User rejects sleep-based polling\n\n"
            f"{_MARKER_END}\n"
        )

        writer = ClaudeCodeWriter()
        recs = [
            _rec(RecommendationTarget.MEMORY_FILE, "Related Codebases", "- web app at ~/Code/web")
        ]
        writer.write(recs, proj, dry_run=False)

        content = memory_md.read_text()
        assert "User rejects sleep-based polling" in content
        assert "web app at ~/Code/web" in content

    def test_section_without_tokens_annotation_round_trips(self, tmp_path):
        """Prior sections emitted without a tokens annotation must still carry forward cleanly."""
        proj = _project(tmp_path)
        claude_md = proj.project_path / "CLAUDE.md"
        claude_md.write_text(
            f"{_MARKER_START}\n"
            "## Headroom Learned Patterns\n"
            "*Auto-generated by `headroom learn` on 2026-01-01 — do not edit manually*\n\n"
            "### Misc\n"
            "- one-liner pattern\n\n"
            f"{_MARKER_END}\n"
        )

        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.CONTEXT_FILE, "Other", "- new one")]
        writer.write(recs, proj, dry_run=False)

        content = claude_md.read_text()
        assert "### Misc" in content
        assert "one-liner pattern" in content
        # No spurious tokens annotation injected for a prior that didn't have one
        misc_idx = content.index("### Misc")
        after_misc = content[misc_idx : misc_idx + 200]
        assert "tokens/session saved" not in after_misc

    def test_appends_to_existing_memory_md(self, tmp_path):
        proj = _project(tmp_path)
        memory_md = proj.data_path / "memory" / "MEMORY.md"
        memory_md.write_text("# Existing Memory\n\nSome facts.\n")

        writer = ClaudeCodeWriter()
        recs = [_rec(RecommendationTarget.MEMORY_FILE, "Retry Prevention", "- New pattern")]
        writer.write(recs, proj, dry_run=False)

        content = memory_md.read_text()
        assert "Existing Memory" in content
        assert "Some facts" in content
        assert "New pattern" in content


class TestParsePriorRecommendations:
    """Direct coverage for _parse_prior_recommendations edge cases."""

    def test_no_marker_block_returns_empty(self):
        """A file without any marker block yields no prior recommendations."""
        assert _parse_prior_recommendations("# Project\n\nJust a regular README.\n") == []

    def test_empty_marker_block_yields_no_recs(self):
        """A marker block with nothing between the markers yields no recs."""
        content = f"prefix\n{_MARKER_START}\n{_MARKER_END}\nsuffix\n"
        assert _parse_prior_recommendations(content) == []

    def test_marker_block_with_empty_heading_is_skipped(self):
        """A stray `### ` (empty heading) inside the block is skipped, not raised."""
        # Leading `### ` with no heading text, followed by a real section.
        content = (
            f"{_MARKER_START}\n"
            "## Headroom Learned Patterns\n"
            "### \n"
            "some orphan content\n"
            "\n"
            "### Real Section\n"
            "- real bullet\n"
            "\n"
            f"{_MARKER_END}\n"
        )
        recs = _parse_prior_recommendations(content)
        # Only the real section is parsed; the empty-heading entry is dropped.
        assert len(recs) == 1
        assert recs[0].section == "Real Section"
        assert "real bullet" in recs[0].content


class TestExtractMarkerBlock:
    """Direct coverage for extract_marker_block."""

    def test_returns_raw_block_when_present(self):
        """Marker block is returned verbatim with delimiters, for LLM prompts."""
        content = (
            "# Project README\n\n"
            "Some text.\n\n"
            f"{_MARKER_START}\n"
            "## Headroom Learned Patterns\n"
            "### Environment\n"
            "- Use uv run python\n"
            f"{_MARKER_END}\n"
            "Trailing text.\n"
        )
        block = extract_marker_block(content)
        assert block is not None
        assert block.startswith(_MARKER_START)
        assert block.endswith(_MARKER_END)
        assert "### Environment" in block
        assert "Use uv run python" in block
        assert "Trailing text." not in block

    def test_returns_none_when_absent(self):
        """File without any marker delimiters yields None."""
        assert extract_marker_block("# Project\n\nJust a regular README.\n") is None

    def test_returns_none_when_only_start_marker(self):
        """Partial/malformed block (start only) yields None — writer expects both delimiters."""
        content = f"prefix\n{_MARKER_START}\n### Something\n- content\n"
        assert extract_marker_block(content) is None

    def test_returns_empty_block_when_markers_are_adjacent(self):
        """A block with nothing between the markers is still returned (caller's choice what to do)."""
        content = f"prefix\n{_MARKER_START}\n{_MARKER_END}\nsuffix\n"
        block = extract_marker_block(content)
        assert block is not None
        assert block == f"{_MARKER_START}\n{_MARKER_END}"
